USE [FundWireInterfaceDB] 
GO 

IF EXISTS(SELECT 1 FROM sys.procedures 
          WHERE Name = 'SP_Insert_FedWireMsgRepo')
BEGIN
    DROP 	PROC SP_Insert_FedWireMsgRepo 
END
GO 
CREATE PROCEDURE SP_Insert_FedWireMsgRepo
  @IMAD varchar(34)= NULL, 
  @OMAD varchar(34)= NULL, 
  @WIREINOUT varchar(64)= NULL, 
  @FormatVersion varchar(2)= NULL, 
  @TestProductionCode varchar(1)= NULL, 
  @MessageDuplication varchar(1)= NULL, 
  @MessageStatus varchar(1)= NULL, 
  @ReceiptDate varchar(4)= NULL, 
  @ReceiptTime varchar(4)= NULL, 
  @ReceiptApplication varchar(4)= NULL, 
  @InputCycleDate varchar(8)= NULL, 
  @InputSource varchar(8)= NULL, 
  @InputSequenceNumber varchar(6)= NULL, 
  @OutputCycleDateDateReceived varchar(8)= NULL, 
  @OutputDestination varchar(8)= NULL, 
  @OutputSequenceNumber varchar(6)= NULL, 
  @OutputDate varchar(4)= NULL, 
  @OutputTime varchar(4)= NULL, 
  @OutputApplication varchar(4)= NULL, 
  @SndFormatVersion varchar(2)= NULL, 
  @SndUserRequestCorrelation varchar(8)= NULL, 
  @SndTestProductionCode varchar(1)= NULL, 
  @SndMessageDuplication varchar(1)= NULL, 
  @TypeSubtype varchar(4)= NULL, 
  @TypeCode varchar(32)= NULL, 
  @TypeCodeDesc varchar(32)= NULL, 
  @TypeSubCode varchar(32)= NULL, 
  @TypeSubCodeDesc varchar(32)= NULL, 
  @SenderABA varchar(9)= NULL, 
  @SenderName varchar(18)= NULL, 
  @SenderReference varchar(16)= NULL, 
  @ReceiverABA varchar(9)= NULL, 
  @ReceiverName varchar(18)= NULL, 
  @BusinessFunction varchar(3)= NULL, 
  @TransactionCode varchar(3)= NULL, 
  @PaymentNotificationContactName varchar(140)= NULL, 
  @TransactionAmount decimal (18, 2)= NULL, 
  @InstructedAmountCurrency varchar(3)= NULL, 
  @InstructedAmount decimal (18, 2)= NULL, 
  @IntemediaryFIIdCode varchar(32)= NULL, 
  @IntemediaryFIIdentifier varchar(34)= NULL, 
  @IntermediaryFIName varchar(35)= NULL, 
  @IntermediaryFIAddressL1 varchar(35)= NULL, 
  @IntermediaryFIAddressL2 varchar(35)= NULL, 
  @IntermediaryFIAddressL3 varchar(35)= NULL, 
  @BeneficiaryFIIdCode varchar(32)= NULL, 
  @BeneficiaryFIIdentifierAccount varchar(34)= NULL, 
  @BeneficiaryFIName varchar(35)= NULL, 
  @BeneficiaryFIAddressL1 varchar(35)= NULL, 
  @BeneficiaryFIAddressL2 varchar(35)= NULL, 
  @BeneficiaryFIAddressL3 varchar(35)= NULL, 
  @BeneficiaryIdCode varchar(32)= NULL, 
  @BeneficiaryIdentifierAccount varchar(34)= NULL, 
  @BeneficiaryName varchar(35)= NULL, 
  @BeneficiaryAddressL1 varchar(35)= NULL, 
  @BeneficiaryAddressL2 varchar(35)= NULL, 
  @BeneficiaryAddressL3 varchar(35)= NULL, 
  @ReferenceForBeneficiary varchar(16)= NULL, 
  @AccountDebitInDrawDownIdCode varchar(32)= NULL, 
  @AccountDebitInDrawDownIdentifier varchar(34)= NULL, 
  @AccountDebitInDrawDownName varchar(35)= NULL, 
  @AccountDebitInDrawDownAddressL1 varchar(35)= NULL, 
  @AccountDebitInDrawDownAddressL2 varchar(35)= NULL, 
  @AccountDebitInDrawDownAddressL3 varchar(35)= NULL, 
  @OriginatorIdCode varchar(32)= NULL, 
  @OriginatorIdentifier varchar(34)= NULL, 
  @OriginatorName varchar(35)= NULL, 
  @OriginatorAddressL1 varchar(35)= NULL, 
  @OriginatorAddressL2 varchar(35)= NULL, 
  @OriginatorAddressL3 varchar(35)= NULL, 
  @OriginatorOptionFIdCode varchar(32)= NULL, 
  @OriginatorOptionFPartyIdentifier varchar(35)= NULL, 
  @OriginatorOptionFPartyName varchar(35)= NULL, 
  @OriginatorOptionFICodeL1 varchar(32)= NULL, 
  @OriginatorOptionFIDetL1 varchar(35)= NULL, 
  @OriginatorOptionFICodeL2 varchar(32)= NULL, 
  @OriginatorOptionFIDetL2 varchar(35)= NULL, 
  @OriginatorOptionFICodeL3 varchar(32)= NULL, 
  @OriginatorOptionFIDetL3 varchar(35)= NULL, 
  @OriginatorFIIdCode varchar(32)= NULL, 
  @OriginatorFIIdentifier varchar(34)= NULL, 
  @OriginatorFIName varchar(35)= NULL, 
  @OriginatorFIAddressL1 varchar(35)= NULL, 
  @OriginatorFIAddressL2 varchar(35)= NULL, 
  @OriginatorFIAddressL3 varchar(35)= NULL, 
  @InstructingFIIdCode varchar(32)= NULL, 
  @InstructingFIIdentifier varchar(34)= NULL, 
  @InstructingFIName varchar(35)= NULL, 
  @InstructingFIAddressL1 varchar(35)= NULL, 
  @InstructingFIAddressL2 varchar(35)= NULL, 
  @InstructingFIAddressL3 varchar(35)= NULL, 
  @DrawDownCreditAccountNumber varchar(9)= NULL, 
  @OriginatortoBeneficiaryInformationL1 varchar(35)= NULL, 
  @OriginatortoBeneficiaryInformationL2 varchar(35)= NULL, 
  @OriginatortoBeneficiaryInformationL3 varchar(35)= NULL, 
  @OriginatortoBeneficiaryInformationL4 varchar(35)= NULL, 
  @ReceiverFIInformation varchar(30)= NULL, 
  @ReceiverFIIAddInformationL1 varchar(33)= NULL, 
  @ReceiverFIIAddInformationL2 varchar(33)= NULL, 
  @ReceiverFIIAddInformationL3 varchar(33)= NULL, 
  @ReceiverFIIAddInformationL4 varchar(33)= NULL, 
  @ReceiverFIIAddInformationL5 varchar(33)= NULL, 
  @IntermediaryFIInformation varchar(30)= NULL, 
  @IntermediaryFIIAddInformationL1 varchar(33)= NULL, 
  @IntermediaryFIIAddInformationL2 varchar(33)= NULL, 
  @IntermediaryFIIAddInformationL3 varchar(33)= NULL, 
  @IntermediaryFIIAddInformationL4 varchar(33)= NULL, 
  @IntermediaryFIIAddInformationL5 varchar(33)= NULL, 
  @BeneficiarysFIInformation varchar(30)= NULL, 
  @BeneficiarysFIInformationL1 varchar(33)= NULL, 
  @BeneficiarysFIInformationL2 varchar(33)= NULL, 
  @BeneficiarysFIInformationL3 varchar(33)= NULL, 
  @BeneficiarysFIInformationL4 varchar(33)= NULL, 
  @BeneficiarysFIInformationL5 varchar(33)= NULL, 
  @BeneficiaryInformation varchar(30)= NULL, 
  @BeneficiaryInformationL1 varchar(33)= NULL, 
  @BeneficiaryInformationL2 varchar(33)= NULL, 
  @BeneficiaryInformationL3 varchar(33)= NULL, 
  @BeneficiaryInformationL4 varchar(33)= NULL, 
  @BeneficiaryInformationL5 varchar(33)= NULL, 
  @SwiftInstructedCurrency varchar(3)= NULL, 
  @SwiftInstructedAmount decimal = NULL, 
  @SwiftOrderingCustomerL1 varchar(35)= NULL, 
  @SwiftOrderingCustomerL2 varchar(35)= NULL, 
  @SwiftOrderingCustomerL3 varchar(35)= NULL, 
  @SwiftOrderingCustomerL4 varchar(35)= NULL, 
  @SwiftOrderingCustomerL5 varchar(35)= NULL, 
  @SwiftOrderingInstitutionL1 varchar(35)= NULL, 
  @SwiftOrderingInstitutionL2 varchar(35)= NULL, 
  @SwiftOrderingInstitutionL3 varchar(35)= NULL, 
  @SwiftOrderingInstitutionL4 varchar(35)= NULL, 
  @SwiftOrderingInstitutionL5 varchar(35)= NULL, 
  @SwiftIntermiediaryInstitutionL1 varchar(35)= NULL, 
  @SwiftIntermiediaryInstitutionL2 varchar(35)= NULL, 
  @SwiftIntermiediaryInstitutionL3 varchar(35)= NULL, 
  @SwiftIntermiediaryInstitutionL4 varchar(35)= NULL, 
  @SwiftIntermiediaryInstitutionL5 varchar(35)= NULL, 
  @SwiftAccountWithInstitutionL1 varchar(35)= NULL, 
  @SwiftAccountWithInstitutionL2 varchar(35)= NULL, 
  @SwiftAccountWithInstitutionL3 varchar(35)= NULL, 
  @SwiftAccountWithInstitutionL4 varchar(35)= NULL, 
  @SwiftAccountWithInstitutionL5 varchar(35)= NULL, 
  @SwiftBeneficiaryCustomerL1 varchar(35)= NULL, 
  @SwiftBeneficiaryCustomerL2 varchar(35)= NULL, 
  @SwiftBeneficiaryCustomerL3 varchar(35)= NULL, 
  @SwiftBeneficiaryCustomerL4 varchar(35)= NULL, 
  @SwiftBeneficiaryCustomerL5 varchar(35)= NULL, 
  @SwiftRemittanceInformationL1 varchar(35)= NULL, 
  @SwiftRemittanceInformationL2 varchar(35)= NULL, 
  @SwiftRemittanceInformationL3 varchar(35)= NULL, 
  @SwiftRemittanceInformationL4 varchar(35)= NULL, 
  @SwiftRemittanceInformationL5 varchar(35)= NULL, 
  @SwiftSenderToReceiverInformationL1 varchar(35)= NULL, 
  @SwiftSenderToReceiverInformationL2 varchar(35)= NULL, 
  @SwiftSenderToReceiverInformationL3 varchar(35)= NULL, 
  @SwiftSenderToReceiverInformationL4 varchar(35)= NULL, 
  @SwiftSenderToReceiverInformationL5 varchar(35)= NULL, 
  @AddendaInformation varchar(max)= NULL, 
  @previousMessageIdentifier varchar(22)= NULL, 
  @NonProcessedInformation varchar(max)= NULL, 
  @FileName varchar(256)= NULL, 
  @RecordNumber numeric(18, 0)= NULL, 
  @LoadStatus varchar(16)= NULL, 
  @LoadRejectReason varchar(512)= NULL, 
  @CreationDate datetime = NULL, 
  @CreatorId varchar(32) = NULL, 
  @UpdateDate datetime = NULL, 
  @UpdatorId varchar(32)= NULL, 
  @DeletedDate datetime = NULL, 
  @DeleteddBy varchar(32)= NULL, 
  @InternalId numeric(18, 0) out,
  @Status varchar(32) out 
  AS
  BEGIN
    set @Status='Inserted'
	IF NOT EXISTS (SELECT * FROM dbo.FedWireMsgRepo WHERE IMAD = @IMAD)	
		BEGIN
		  INSERT INTO dbo.FedWireMsgRepo (
			[IMAD], 
			[OMAD], 
			[WIREINOUT], 
			[FormatVersion], 
			[TestProductionCode], 
			[MessageDuplication], 
			[MessageStatus], 
			[ReceiptDate], 
			[ReceiptTime], 
			[ReceiptApplication], 
			[InputCycleDate], 
			[InputSource], 
			[InputSequenceNumber], 
			[OutputCycleDateDateReceived], 
			[OutputDestination], 
			[OutputSequenceNumber], 
			[OutputDate], 
			[OutputTime], 
			[OutputApplication], 
			[SndFormatVersion], 
			[SndUserRequestCorrelation], 
			[SndTestProductionCode], 
			[SndMessageDuplication], 
			[TypeSubtype], 
			[TypeCode], 
			[TypeCodeDesc], 
			[TypeSubCode], 
			[TypeSubCodeDesc], 
			[SenderABA], 
			[SenderName], 
			[SenderReference], 
			[ReceiverABA], 
			[ReceiverName], 
			[BusinessFunction], 
			[TransactionCode], 
			[PaymentNotificationContactName], 
			[TransactionAmount], 
			[InstructedAmountCurrency], 
			[InstructedAmount], 
			[IntemediaryFIIdCode], 
			[IntemediaryFIIdentifier], 
			[IntermediaryFIName], 
			[IntermediaryFIAddressL1], 
			[IntermediaryFIAddressL2], 
			[IntermediaryFIAddressL3], 
			[BeneficiaryFIIdCode], 
			[BeneficiaryFIIdentifierAccount], 
			[BeneficiaryFIName], 
			[BeneficiaryFIAddressL1], 
			[BeneficiaryFIAddressL2], 
			[BeneficiaryFIAddressL3], 
			[BeneficiaryIdCode], 
			[BeneficiaryIdentifierAccount], 
			[BeneficiaryName], 
			[BeneficiaryAddressL1], 
			[BeneficiaryAddressL2], 
			[BeneficiaryAddressL3], 
			[ReferenceForBeneficiary], 
			[AccountDebitInDrawDownIdCode], 
			[AccountDebitInDrawDownIdentifier], 
			[AccountDebitInDrawDownName], 
			[AccountDebitInDrawDownAddressL1], 
			[AccountDebitInDrawDownAddressL2], 
			[AccountDebitInDrawDownAddressL3], 
			[OriginatorIdCode], 
			[OriginatorIdentifier], 
			[OriginatorName], 
			[OriginatorAddressL1], 
			[OriginatorAddressL2], 
			[OriginatorAddressL3], 
			[OriginatorOptionFIdCode], 
			[OriginatorOptionFPartyIdentifier], 
			[OriginatorOptionFPartyName], 
			[OriginatorOptionFICodeL1], 
			[OriginatorOptionFIDetL1], 
			[OriginatorOptionFICodeL2], 
			[OriginatorOptionFIDetL2], 
			[OriginatorOptionFICodeL3], 
			[OriginatorOptionFIDetL3], 
			[OriginatorFIIdCode], 
			[OriginatorFIIdentifier], 
			[OriginatorFIName], 
			[OriginatorFIAddressL1], 
			[OriginatorFIAddressL2], 
			[OriginatorFIAddressL3], 
			[InstructingFIIdCode], 
			[InstructingFIIdentifier], 
			[InstructingFIName], 
			[InstructingFIAddressL1], 
			[InstructingFIAddressL2], 
			[InstructingFIAddressL3], 
			[DrawDownCreditAccountNumber], 
			[OriginatortoBeneficiaryInformationL1], 
			[OriginatortoBeneficiaryInformationL2], 
			[OriginatortoBeneficiaryInformationL3], 
			[OriginatortoBeneficiaryInformationL4], 
			[ReceiverFIInformation], 
			[ReceiverFIIAddInformationL1], 
			[ReceiverFIIAddInformationL2], 
			[ReceiverFIIAddInformationL3], 
			[ReceiverFIIAddInformationL4], 
			[ReceiverFIIAddInformationL5], 
			[IntermediaryFIInformation], 
			[IntermediaryFIIAddInformationL1], 
			[IntermediaryFIIAddInformationL2], 
			[IntermediaryFIIAddInformationL3], 
			[IntermediaryFIIAddInformationL4], 
			[IntermediaryFIIAddInformationL5], 
			[BeneficiarysFIInformation], 
			[BeneficiarysFIInformationL1], 
			[BeneficiarysFIInformationL2], 
			[BeneficiarysFIInformationL3], 
			[BeneficiarysFIInformationL4], 
			[BeneficiarysFIInformationL5], 
			[BeneficiaryInformation], 
			[BeneficiaryInformationL1], 
			[BeneficiaryInformationL2], 
			[BeneficiaryInformationL3], 
			[BeneficiaryInformationL4], 
			[BeneficiaryInformationL5], 
			[SwiftInstructedCurrency], 
			[SwiftInstructedAmount], 
			[SwiftOrderingCustomerL1], 
			[SwiftOrderingCustomerL2], 
			[SwiftOrderingCustomerL3], 
			[SwiftOrderingCustomerL4], 
			[SwiftOrderingCustomerL5], 
			[SwiftOrderingInstitutionL1], 
			[SwiftOrderingInstitutionL2], 
			[SwiftOrderingInstitutionL3], 
			[SwiftOrderingInstitutionL4], 
			[SwiftOrderingInstitutionL5], 
			[SwiftIntermiediaryInstitutionL1], 
			[SwiftIntermiediaryInstitutionL2], 
			[SwiftIntermiediaryInstitutionL3], 
			[SwiftIntermiediaryInstitutionL4], 
			[SwiftIntermiediaryInstitutionL5], 
			[SwiftAccountWithInstitutionL1], 
			[SwiftAccountWithInstitutionL2], 
			[SwiftAccountWithInstitutionL3], 
			[SwiftAccountWithInstitutionL4], 
			[SwiftAccountWithInstitutionL5], 
			[SwiftBeneficiaryCustomerL1], 
			[SwiftBeneficiaryCustomerL2], 
			[SwiftBeneficiaryCustomerL3], 
			[SwiftBeneficiaryCustomerL4], 
			[SwiftBeneficiaryCustomerL5], 
			[SwiftRemittanceInformationL1], 
			[SwiftRemittanceInformationL2], 
			[SwiftRemittanceInformationL3], 
			[SwiftRemittanceInformationL4], 
			[SwiftRemittanceInformationL5], 
			[SwiftSenderToReceiverInformationL1], 
			[SwiftSenderToReceiverInformationL2], 
			[SwiftSenderToReceiverInformationL3], 
			[SwiftSenderToReceiverInformationL4], 
			[SwiftSenderToReceiverInformationL5], 
			[AddendaInformation], 
			[previousMessageIdentifier], 
			[NonProcessedInformation], 
			[FileName], 
			[RecordNumber], 
			[LoadStatus], 
			[LoadRejectReason], 
			[CreationDate], 
			[CreatorId], 
			[UpdateDate], 
			[UpdatorId], 
			[DeletedDate], 
			[DeleteddBy]
		  ) output inserted.* 
		SELECT 
		  @IMAD, 
		  @OMAD, 
		  @WIREINOUT, 
		  @FormatVersion, 
		  @TestProductionCode, 
		  @MessageDuplication, 
		  @MessageStatus, 
		  @ReceiptDate, 
		  @ReceiptTime, 
		  @ReceiptApplication, 
		  @InputCycleDate, 
		  @InputSource, 
		  @InputSequenceNumber, 
		  @OutputCycleDateDateReceived, 
		  @OutputDestination, 
		  @OutputSequenceNumber, 
		  @OutputDate, 
		  @OutputTime, 
		  @OutputApplication, 
		  @SndFormatVersion, 
		  @SndUserRequestCorrelation, 
		  @SndTestProductionCode, 
		  @SndMessageDuplication, 
		  @TypeSubtype, 
		  @TypeCode, 
		  @TypeCodeDesc, 
		  @TypeSubCode, 
		  @TypeSubCodeDesc, 
		  @SenderABA, 
		  @SenderName, 
		  @SenderReference, 
		  @ReceiverABA, 
		  @ReceiverName, 
		  @BusinessFunction, 
		  @TransactionCode, 
		  @PaymentNotificationContactName, 
		  @TransactionAmount, 
		  @InstructedAmountCurrency, 
		  @InstructedAmount, 
		  @IntemediaryFIIdCode, 
		  @IntemediaryFIIdentifier, 
		  @IntermediaryFIName, 
		  @IntermediaryFIAddressL1, 
		  @IntermediaryFIAddressL2, 
		  @IntermediaryFIAddressL3, 
		  @BeneficiaryFIIdCode, 
		  @BeneficiaryFIIdentifierAccount, 
		  @BeneficiaryFIName, 
		  @BeneficiaryFIAddressL1, 
		  @BeneficiaryFIAddressL2, 
		  @BeneficiaryFIAddressL3, 
		  @BeneficiaryIdCode, 
		  @BeneficiaryIdentifierAccount, 
		  @BeneficiaryName, 
		  @BeneficiaryAddressL1, 
		  @BeneficiaryAddressL2, 
		  @BeneficiaryAddressL3, 
		  @ReferenceForBeneficiary, 
		  @AccountDebitInDrawDownIdCode, 
		  @AccountDebitInDrawDownIdentifier, 
		  @AccountDebitInDrawDownName, 
		  @AccountDebitInDrawDownAddressL1, 
		  @AccountDebitInDrawDownAddressL2, 
		  @AccountDebitInDrawDownAddressL3, 
		  @OriginatorIdCode, 
		  @OriginatorIdentifier, 
		  @OriginatorName, 
		  @OriginatorAddressL1, 
		  @OriginatorAddressL2, 
		  @OriginatorAddressL3, 
		  @OriginatorOptionFIdCode, 
		  @OriginatorOptionFPartyIdentifier, 
		  @OriginatorOptionFPartyName, 
		  @OriginatorOptionFICodeL1, 
		  @OriginatorOptionFIDetL1, 
		  @OriginatorOptionFICodeL2, 
		  @OriginatorOptionFIDetL2, 
		  @OriginatorOptionFICodeL3, 
		  @OriginatorOptionFIDetL3, 
		  @OriginatorFIIdCode, 
		  @OriginatorFIIdentifier, 
		  @OriginatorFIName, 
		  @OriginatorFIAddressL1, 
		  @OriginatorFIAddressL2, 
		  @OriginatorFIAddressL3, 
		  @InstructingFIIdCode, 
		  @InstructingFIIdentifier, 
		  @InstructingFIName, 
		  @InstructingFIAddressL1, 
		  @InstructingFIAddressL2, 
		  @InstructingFIAddressL3, 
		  @DrawDownCreditAccountNumber, 
		  @OriginatortoBeneficiaryInformationL1, 
		  @OriginatortoBeneficiaryInformationL2, 
		  @OriginatortoBeneficiaryInformationL3, 
		  @OriginatortoBeneficiaryInformationL4, 
		  @ReceiverFIInformation, 
		  @ReceiverFIIAddInformationL1, 
		  @ReceiverFIIAddInformationL2, 
		  @ReceiverFIIAddInformationL3, 
		  @ReceiverFIIAddInformationL4, 
		  @ReceiverFIIAddInformationL5, 
		  @IntermediaryFIInformation, 
		  @IntermediaryFIIAddInformationL1, 
		  @IntermediaryFIIAddInformationL2, 
		  @IntermediaryFIIAddInformationL3, 
		  @IntermediaryFIIAddInformationL4, 
		  @IntermediaryFIIAddInformationL5, 
		  @BeneficiarysFIInformation, 
		  @BeneficiarysFIInformationL1, 
		  @BeneficiarysFIInformationL2, 
		  @BeneficiarysFIInformationL3, 
		  @BeneficiarysFIInformationL4, 
		  @BeneficiarysFIInformationL5, 
		  @BeneficiaryInformation, 
		  @BeneficiaryInformationL1, 
		  @BeneficiaryInformationL2, 
		  @BeneficiaryInformationL3, 
		  @BeneficiaryInformationL4, 
		  @BeneficiaryInformationL5, 
		  @SwiftInstructedCurrency, 
		  @SwiftInstructedAmount, 
		  @SwiftOrderingCustomerL1, 
		  @SwiftOrderingCustomerL2, 
		  @SwiftOrderingCustomerL3, 
		  @SwiftOrderingCustomerL4, 
		  @SwiftOrderingCustomerL5, 
		  @SwiftOrderingInstitutionL1, 
		  @SwiftOrderingInstitutionL2, 
		  @SwiftOrderingInstitutionL3, 
		  @SwiftOrderingInstitutionL4, 
		  @SwiftOrderingInstitutionL5, 
		  @SwiftIntermiediaryInstitutionL1, 
		  @SwiftIntermiediaryInstitutionL2, 
		  @SwiftIntermiediaryInstitutionL3, 
		  @SwiftIntermiediaryInstitutionL4, 
		  @SwiftIntermiediaryInstitutionL5, 
		  @SwiftAccountWithInstitutionL1, 
		  @SwiftAccountWithInstitutionL2, 
		  @SwiftAccountWithInstitutionL3, 
		  @SwiftAccountWithInstitutionL4, 
		  @SwiftAccountWithInstitutionL5, 
		  @SwiftBeneficiaryCustomerL1, 
		  @SwiftBeneficiaryCustomerL2, 
		  @SwiftBeneficiaryCustomerL3, 
		  @SwiftBeneficiaryCustomerL4, 
		  @SwiftBeneficiaryCustomerL5, 
		  @SwiftRemittanceInformationL1, 
		  @SwiftRemittanceInformationL2, 
		  @SwiftRemittanceInformationL3, 
		  @SwiftRemittanceInformationL4, 
		  @SwiftRemittanceInformationL5, 
		  @SwiftSenderToReceiverInformationL1, 
		  @SwiftSenderToReceiverInformationL2, 
		  @SwiftSenderToReceiverInformationL3, 
		  @SwiftSenderToReceiverInformationL4, 
		  @SwiftSenderToReceiverInformationL5, 
		  @AddendaInformation, 
		  @previousMessageIdentifier, 
		  @NonProcessedInformation, 
		  @FileName, 
		  @RecordNumber, 
		  @LoadStatus, 
		  @LoadRejectReason, 
		  @CreationDate, 
		  @CreatorId, 
		  @UpdateDate, 
		  @UpdatorId, 
		  @DeletedDate, 
		  @DeleteddBy;
		  set @Status='Inserted'
          set @InternalId = @@IDENTITY;		  /*= @@IDENTITY */
		END
	ELSE
		BEGIN 
			set @Status='Duplicate';
			set @InternalId =0
		END 
END
GO
