IF OBJECT_ID('SP_Insert_FedMessageWire', 'P') IS NOT NULL 
BEGIN 
DROP PROC SP_Insert_FedMessageWire
END
GO
  CREATE PROCEDURE SP_Insert_FedMessageWire @MessageId varchar(32),
  @MessageReference varchar(32) = NULL,
  @MessageOrigin varchar(10) = NULL,
  @OrigineName varchar(64) = NULL,
  @IncomingOutGoing varchar(16) = NULL,
  @FileId numeric = NULL,
  @ClientId varchar(32) = NULL,
  @DateReceived datetime = NULL,
  @DateLoaded datetime = NULL,
  @SenderFormatVersion varchar(2) = NULL,
  @SenderUserRequestCorrelation varchar(8) = NULL,
  @SenderProductionCode varchar(1) = NULL,
  @SenderMessageDuplicationCode varchar(1) = NULL,
  @MessageType varchar(2) = NULL,
  @MessageTypeSubType varchar(2) = NULL,
  @ImadCycleDate varchar(8) = NULL,
  @ImadSource varchar(8) = NULL,
  @ImadSequenceNumber varchar(6) = NULL,
  @Amount decimal = NULL,
  @SenderABANumber varchar(9) = NULL,
  @SenderShortName varchar(18) = NULL,
  @ReceiverABANumber varchar(9) = NULL,
  @ReceiverShortName varchar(18) = NULL,
  @BusinessFunctionCode varchar(3) = NULL,
  @SenderReference varchar(16) = NULL,
  @PreviousMessageId varchar(22) = NULL,
  @LocalInstrumentCode varchar(4) = NULL,
  @ProprietaryCode varchar(35) = NULL,
  @ChargesDetail varchar(1) = NULL,
  @ChargeCurrency1 varchar(3) = NULL,
  @ChargeAmount1 decimal = NULL,
  @ChargeCurrency2 varchar(3) = NULL,
  @ChargeAmount2 decimal = NULL,
  @ChargeCurrency3 varchar(3) = NULL,
  @ChargeAmount3 decimal = NULL,
  @ChargeCurrency4 varchar(3) = NULL,
  @ChargeAmount4 decimal = NULL,
  @InstructedCurrency varchar(3) = NULL,
  @InstructedAmount decimal = NULL,
  @ExchangeRate decimal = NULL,
  @ReferenceforBeneficiary varchar(16) = NULL,
  @OriginatorOptionFPartyIdentifier varchar(4) = NULL,
  @OriginatorOptionFPartyUniqueIdentifier varchar(31) = NULL,
  @OriginatorOptionFPartyNameCode varchar(1) = NULL,
  @OriginatorOptionFPartyName varchar(34) = NULL,
  @AccountCreditedinDrawDownABA varchar(9) = NULL,
  @OriginatortoBeneficiaryInfL1 varchar(35) = NULL,
  @OriginatortoBeneficiaryInfL2 varchar(35) = NULL,
  @OriginatortoBeneficiaryInfL3 varchar(35) = NULL,
  @OriginatortoBeneficiaryInfL4 varchar(35) = NULL,
  @MethodOfPaymentCode varchar(5) = NULL,
  @MethodOfPaymentAdditionalInformation varchar(30) = NULL,
  @FItoFIInformationL1 varchar(35) = NULL,
  @FItoFIInformationL2 varchar(35) = NULL,
  @FItoFIInformationL3 varchar(35) = NULL,
  @FItoFIInformationL4 varchar(35) = NULL,
  @FItoFIInformationL5 varchar(35) = NULL,
  @FItoFIInformationL6 varchar(35) = NULL,
  @DateofRemittanceDocument datetime = NULL,
  @MessageDispositionFormatVersion varchar(2) = NULL,
  @MessageDispositionProductionCode varchar(1) = NULL,
  @MessageDispositionMessageDuplicationCode varchar(1) = NULL,
  @MessageDispositionStatusIndicator varchar(1) = NULL,
  @ReceiptDateMMDD varchar(4) = NULL,
  @ReceiptTimeHHMM varchar(4) = NULL,
  @ReceiptApplicationID varchar(4) = NULL,
  @OmadCycleDate varchar(8) = NULL,
  @OmadDestinationId varchar(8) = NULL,
  @OmadOutputSequenceNumber varchar(6) = NULL,
  @OmadOutputDateDateMMDD varchar(4) = NULL,
  @OmadOutputTimeHHMM varchar(4) = NULL,
  @OmadOutputApplicationID varchar(4) = NULL,
  @ErrorCatecoryCode varchar(1) = NULL,
  @ErrorCode varchar(3) = NULL,
  @ErrorDescription varchar(35) = NULL,
  @LoadStatus varchar(16) = NULL,
  @LoadRejectReason varchar(512) = NULL,
  @CreationDate datetime = NULL,
  @CreatorId varchar(32) = NULL,
  @UpdateDate datetime = NULL,
  @UpdatorId varchar(32) = NULL,
  @ID numeric(18, 0) out AS BEGIN
INSERT INTO
  dbo.FedMessageWire (
    MessageId,
    MessageReference,
    MessageOrigin,
    OrigineName,
    IncomingOutGoing,
    FileId,
    ClientId,
    DateReceived,
    DateLoaded,
    SenderFormatVersion,
    SenderUserRequestCorrelation,
    SenderProductionCode,
    SenderMessageDuplicationCode,
    MessageType,
    MessageTypeSubType,
    ImadCycleDate,
    ImadSource,
    ImadSequenceNumber,
    Amount,
    SenderABANumber,
    SenderShortName,
    ReceiverABANumber,
    ReceiverShortName,
    BusinessFunctionCode,
    SenderReference,
    PreviousMessageId,
    LocalInstrumentCode,
    ProprietaryCode,
    ChargesDetail,
    ChargeCurrency1,
    ChargeAmount1,
    ChargeCurrency2,
    ChargeAmount2,
    ChargeCurrency3,
    ChargeAmount3,
    ChargeCurrency4,
    ChargeAmount4,
    InstructedCurrency,
    InstructedAmount,
    ExchangeRate,
    ReferenceforBeneficiary,
    OriginatorOptionFPartyIdentifier,
    OriginatorOptionFPartyUniqueIdentifier,
    OriginatorOptionFPartyNameCode,
    OriginatorOptionFPartyName,
    AccountCreditedinDrawDownABA,
    OriginatortoBeneficiaryInfL1,
    OriginatortoBeneficiaryInfL2,
    OriginatortoBeneficiaryInfL3,
    OriginatortoBeneficiaryInfL4,
    MethodOfPaymentCode,
    MethodOfPaymentAdditionalInformation,
    FItoFIInformationL1,
    FItoFIInformationL2,
    FItoFIInformationL3,
    FItoFIInformationL4,
    FItoFIInformationL5,
    FItoFIInformationL6,
    DateofRemittanceDocument,
    MessageDispositionFormatVersion,
    MessageDispositionProductionCode,
    MessageDispositionMessageDuplicationCode,
    MessageDispositionStatusIndicator,
    ReceiptDateMMDD,
    ReceiptTimeHHMM,
    ReceiptApplicationID,
    OmadCycleDate,
    OmadDestinationId,
    OmadOutputSequenceNumber,
    OmadOutputDateDateMMDD,
    OmadOutputTimeHHMM,
    OmadOutputApplicationID,
    ErrorCatecoryCode,
    ErrorCode,
    ErrorDescription,
    LoadStatus,
    LoadRejectReason,
    CreationDate,
    CreatorId,
    UpdateDate,
    UpdatorId
  )
    output inserted.*
SELECT
  @MessageId,
  @MessageReference,
  @MessageOrigin,
  @OrigineName,
  @IncomingOutGoing,
  @FileId,
  @ClientId,
  @DateReceived,
  @DateLoaded,
  @SenderFormatVersion,
  @SenderUserRequestCorrelation,
  @SenderProductionCode,
  @SenderMessageDuplicationCode,
  @MessageType,
  @MessageTypeSubType,
  @ImadCycleDate,
  @ImadSource,
  @ImadSequenceNumber,
  @Amount,
  @SenderABANumber,
  @SenderShortName,
  @ReceiverABANumber,
  @ReceiverShortName,
  @BusinessFunctionCode,
  @SenderReference,
  @PreviousMessageId,
  @LocalInstrumentCode,
  @ProprietaryCode,
  @ChargesDetail,
  @ChargeCurrency1,
  @ChargeAmount1,
  @ChargeCurrency2,
  @ChargeAmount2,
  @ChargeCurrency3,
  @ChargeAmount3,
  @ChargeCurrency4,
  @ChargeAmount4,
  @InstructedCurrency,
  @InstructedAmount,
  @ExchangeRate,
  @ReferenceforBeneficiary,
  @OriginatorOptionFPartyIdentifier,
  @OriginatorOptionFPartyUniqueIdentifier,
  @OriginatorOptionFPartyNameCode,
  @OriginatorOptionFPartyName,
  @AccountCreditedinDrawDownABA,
  @OriginatortoBeneficiaryInfL1,
  @OriginatortoBeneficiaryInfL2,
  @OriginatortoBeneficiaryInfL3,
  @OriginatortoBeneficiaryInfL4,
  @MethodOfPaymentCode,
  @MethodOfPaymentAdditionalInformation,
  @FItoFIInformationL1,
  @FItoFIInformationL2,
  @FItoFIInformationL3,
  @FItoFIInformationL4,
  @FItoFIInformationL5,
  @FItoFIInformationL6,
  @DateofRemittanceDocument,
  @MessageDispositionFormatVersion,
  @MessageDispositionProductionCode,
  @MessageDispositionMessageDuplicationCode,
  @MessageDispositionStatusIndicator,
  @ReceiptDateMMDD,
  @ReceiptTimeHHMM,
  @ReceiptApplicationID,
  @OmadCycleDate,
  @OmadDestinationId,
  @OmadOutputSequenceNumber,
  @OmadOutputDateDateMMDD,
  @OmadOutputTimeHHMM,
  @OmadOutputApplicationID,
  @ErrorCatecoryCode,
  @ErrorCode,
  @ErrorDescription,
  @LoadStatus,
  @LoadRejectReason,
  @CreationDate,
  @CreatorId,
  @UpdateDate,
  @UpdatorId;
set
  @ID = @@IDENTITY
END
GO