IF OBJECT_ID('SP_Insert_RemittanceDocumentInvoice', 'P') IS NOT NULL 
BEGIN DROP PROC 
SP_Insert_RemittanceDocumentInvoice
END
GO
  CREATE PROCEDURE SP_Insert_RemittanceDocumentInvoice @MessageReference varchar(32) = NULL,
  @MessageOrigin varchar(10) = NULL,
  @OrigineName varchar(64) = NULL,
  @IncomingOutGoing varchar(16) = NULL,
  @MessageId varchar(32) = NULL,
  @SequenceNumber int = NULL,
  @OriginatorIdentificationType varchar(2) = NULL,
  @OriginatorIdentificationCode varchar(4) = NULL,
  @OriginatorName varchar(140) = NULL,
  @OriginatorIdentificationNumber varchar(35) = NULL,
  @OriginatorIdentificationNumberIssuer varchar(35) = NULL,
  @OriginatorDateOfBirth varchar(8) = NULL,
  @OriginatorPlaceOfBirth varchar(74) = NULL,
  @OriginatorAddressType varchar(4) = NULL,
  @OriginatorDepartment varchar(70) = NULL,
  @OriginatorSubDepartment varchar(70) = NULL,
  @OriginatorStreetName varchar(70) = NULL,
  @OriginatorBuildingNumber varchar(16) = NULL,
  @OriginatorPostCode varchar(16) = NULL,
  @OriginatorTownName varchar(35) = NULL,
  @OriginatorCountryStateSubDivision varchar(35) = NULL,
  @OriginatorCountry varchar(2) = NULL,
  @OriginatorAddressLine1 varchar(70) = NULL,
  @OriginatorAddressLine2 varchar(70) = NULL,
  @OriginatorAddressLine3 varchar(70) = NULL,
  @OriginatorAddressLine4 varchar(70) = NULL,
  @OriginatorAddressLine5 varchar(70) = NULL,
  @OriginatorAddressLine6 varchar(70) = NULL,
  @OriginatorAddressLine7 varchar(70) = NULL,
  @OriginatorCountryOfResidence varchar(2) = NULL,
  @OriginatorContactName varchar(140) = NULL,
  @OriginatorContactPhoneNumber varchar(35) = NULL,
  @OriginatorContactMobileNumber varchar(35) = NULL,
  @OriginatorContactFaxNumber varchar(35) = NULL,
  @OriginatorContactElectronicAddress varchar(2048) = NULL,
  @OriginatorContactOtherInfo varchar(35) = NULL,
  @BeneficiaryIdentificationType varchar(4) = NULL,
  @BeneficiaryIdentificationCode varchar(4) = NULL,
  @BeneficiaryName varchar(140) = NULL,
  @BeneficiaryIdentificationNumber varchar(35) = NULL,
  @BeneficiaryIdentificationNumberIssuer varchar(35) = NULL,
  @BeneficiaryDateOfbirth varchar(8) = NULL,
  @BeneficiaryPlaceOfBirth varchar(74) = NULL,
  @BeneficiaryAddressType varchar(4) = NULL,
  @BeneficiaryDepartment varchar(70) = NULL,
  @BeneficiarySubDepartment varchar(70) = NULL,
  @BeneficiaryStreetName varchar(70) = NULL,
  @BeneficiaryBuildingNumber varchar(16) = NULL,
  @BeneficiaryPostCode varchar(16) = NULL,
  @BeneficiaryTownName varchar(35) = NULL,
  @BeneficiaryCountryStateSubDivision varchar(35) = NULL,
  @BeneficiaryCountry varchar(2) = NULL,
  @BeneficiaryAddressLine1 varchar(70) = NULL,
  @BeneficiaryAddressLine2 varchar(70) = NULL,
  @BeneficiaryAddressLine3 varchar(70) = NULL,
  @BeneficiaryAddressLine4 varchar(70) = NULL,
  @BeneficiaryAddressLine5 varchar(70) = NULL,
  @BeneficiaryAddressLine6 varchar(70) = NULL,
  @BeneficiaryAddressLine7 varchar(70) = NULL,
  @BeneficiaryCountryOfResidence varchar(2) = NULL,
  @ActualAmountPaidCurrency varchar(3) = NULL,
  @ActualAmountPaid decimal = NULL,
  @GrossAmountCurrency varchar(3) = NULL,
  @GrossAmount decimal = NULL,
  @SecondaryDocumentTypeCode varchar(4) = NULL,
  @SecondaryProprietaryDocumentTypeCode varchar(35) = NULL,
  @SecondaryDocumentIdentificationNumber varchar(35) = NULL,
  @SecondaryIssuer varchar(35) = NULL,
  @SecondaryFreeTextL1 varchar(140) = NULL,
  @SecondaryFreeTextL2 varchar(140) = NULL,
  @SecondaryFreeTextL3 varchar(140) = NULL,
  @ID numeric(18, 0) out AS BEGIN
INSERT INTO
  dbo.RemittanceDocumentInvoice (
    MessageReference,
    MessageOrigin,
    OrigineName,
    IncomingOutGoing,
    MessageId,
    SequenceNumber,
    OriginatorIdentificationType,
    OriginatorIdentificationCode,
    OriginatorName,
    OriginatorIdentificationNumber,
    OriginatorIdentificationNumberIssuer,
    OriginatorDateOfBirth,
    OriginatorPlaceOfBirth,
    OriginatorAddressType,
    OriginatorDepartment,
    OriginatorSubDepartment,
    OriginatorStreetName,
    OriginatorBuildingNumber,
    OriginatorPostCode,
    OriginatorTownName,
    OriginatorCountryStateSubDivision,
    OriginatorCountry,
    OriginatorAddressLine1,
    OriginatorAddressLine2,
    OriginatorAddressLine3,
    OriginatorAddressLine4,
    OriginatorAddressLine5,
    OriginatorAddressLine6,
    OriginatorAddressLine7,
    OriginatorCountryOfResidence,
    OriginatorContactName,
    OriginatorContactPhoneNumber,
    OriginatorContactMobileNumber,
    OriginatorContactFaxNumber,
    OriginatorContactElectronicAddress,
    OriginatorContactOtherInfo,
    BeneficiaryIdentificationType,
    BeneficiaryIdentificationCode,
    BeneficiaryName,
    BeneficiaryIdentificationNumber,
    BeneficiaryIdentificationNumberIssuer,
    BeneficiaryDateOfbirth,
    BeneficiaryPlaceOfBirth,
    BeneficiaryAddressType,
    BeneficiaryDepartment,
    BeneficiarySubDepartment,
    BeneficiaryStreetName,
    BeneficiaryBuildingNumber,
    BeneficiaryPostCode,
    BeneficiaryTownName,
    BeneficiaryCountryStateSubDivision,
    BeneficiaryCountry,
    BeneficiaryAddressLine1,
    BeneficiaryAddressLine2,
    BeneficiaryAddressLine3,
    BeneficiaryAddressLine4,
    BeneficiaryAddressLine5,
    BeneficiaryAddressLine6,
    BeneficiaryAddressLine7,
    BeneficiaryCountryOfResidence,
    ActualAmountPaidCurrency,
    ActualAmountPaid,
    GrossAmountCurrency,
    GrossAmount,
    SecondaryDocumentTypeCode,
    SecondaryProprietaryDocumentTypeCode,
    SecondaryDocumentIdentificationNumber,
    SecondaryIssuer,
    SecondaryFreeTextL1,
    SecondaryFreeTextL2,
    SecondaryFreeTextL3
  )
output inserted.*
SELECT
  @MessageReference,
  @MessageOrigin,
  @OrigineName,
  @IncomingOutGoing,
  @MessageId,
  @SequenceNumber,
  @OriginatorIdentificationType,
  @OriginatorIdentificationCode,
  @OriginatorName,
  @OriginatorIdentificationNumber,
  @OriginatorIdentificationNumberIssuer,
  @OriginatorDateOfBirth,
  @OriginatorPlaceOfBirth,
  @OriginatorAddressType,
  @OriginatorDepartment,
  @OriginatorSubDepartment,
  @OriginatorStreetName,
  @OriginatorBuildingNumber,
  @OriginatorPostCode,
  @OriginatorTownName,
  @OriginatorCountryStateSubDivision,
  @OriginatorCountry,
  @OriginatorAddressLine1,
  @OriginatorAddressLine2,
  @OriginatorAddressLine3,
  @OriginatorAddressLine4,
  @OriginatorAddressLine5,
  @OriginatorAddressLine6,
  @OriginatorAddressLine7,
  @OriginatorCountryOfResidence,
  @OriginatorContactName,
  @OriginatorContactPhoneNumber,
  @OriginatorContactMobileNumber,
  @OriginatorContactFaxNumber,
  @OriginatorContactElectronicAddress,
  @OriginatorContactOtherInfo,
  @BeneficiaryIdentificationType,
  @BeneficiaryIdentificationCode,
  @BeneficiaryName,
  @BeneficiaryIdentificationNumber,
  @BeneficiaryIdentificationNumberIssuer,
  @BeneficiaryDateOfbirth,
  @BeneficiaryPlaceOfBirth,
  @BeneficiaryAddressType,
  @BeneficiaryDepartment,
  @BeneficiarySubDepartment,
  @BeneficiaryStreetName,
  @BeneficiaryBuildingNumber,
  @BeneficiaryPostCode,
  @BeneficiaryTownName,
  @BeneficiaryCountryStateSubDivision,
  @BeneficiaryCountry,
  @BeneficiaryAddressLine1,
  @BeneficiaryAddressLine2,
  @BeneficiaryAddressLine3,
  @BeneficiaryAddressLine4,
  @BeneficiaryAddressLine5,
  @BeneficiaryAddressLine6,
  @BeneficiaryAddressLine7,
  @BeneficiaryCountryOfResidence,
  @ActualAmountPaidCurrency,
  @ActualAmountPaid,
  @GrossAmountCurrency,
  @GrossAmount,
  @SecondaryDocumentTypeCode,
  @SecondaryProprietaryDocumentTypeCode,
  @SecondaryDocumentIdentificationNumber,
  @SecondaryIssuer,
  @SecondaryFreeTextL1,
  @SecondaryFreeTextL2,
  @SecondaryFreeTextL3;
set
  @ID = @@IDENTITY
END
GO