IF OBJECT_ID('SP_Insert_SwiftData', 'P') IS NOT NULL 
BEGIN 
DROP PROC SP_Insert_SwiftData
END
GO
  CREATE PROCEDURE SP_Insert_SwiftData @MessageReference varchar(32) = NULL,
  @MessageOrigin varchar(10) = NULL,
  @OrigineName varchar(64) = NULL,
  @IncomingOutGoing varchar(16) = NULL,
  @MessageId varchar(32) = NULL,
  @SequenceNumber int = NULL,
  @InstructedCurrency varchar(3) = NULL,
  @InstructedAmount decimal = NULL,
  @OrderingCustomerL1 varchar(35) = NULL,
  @OrderingCustomerL2 varchar(35) = NULL,
  @OrderingCustomerL3 varchar(35) = NULL,
  @OrderingCustomerL4 varchar(35) = NULL,
  @OrderingCustomerL5 varchar(35) = NULL,
  @IntermediaryInstitutionL1 varchar(35) = NULL,
  @IntermediaryInstitutionL2 varchar(35) = NULL,
  @IntermediaryInstitutionL3 varchar(35) = NULL,
  @IntermediaryInstitutionL4 varchar(35) = NULL,
  @IntermediaryInstitutionL5 varchar(35) = NULL,
  @AccountwithInstitutionL1 varchar(35) = NULL,
  @AccountwithInstitutionL2 varchar(35) = NULL,
  @AccountwithInstitutionL3 varchar(35) = NULL,
  @AccountwithInstitutionL4 varchar(35) = NULL,
  @AccountwithInstitutionL5 varchar(35) = NULL,
  @BeneficiaryCustomerL1 varchar(35) = NULL,
  @BeneficiaryCustomerL2 varchar(35) = NULL,
  @BeneficiaryCustomerL3 varchar(35) = NULL,
  @BeneficiaryCustomerL4 varchar(35) = NULL,
  @BeneficiaryCustomerL5 varchar(35) = NULL,
  @RemittanceInformationL1 varchar(35) = NULL,
  @RemittanceInformationL2 varchar(35) = NULL,
  @RemittanceInformationL3 varchar(35) = NULL,
  @RemittanceInformationL4 varchar(35) = NULL,
  @RemittanceInformationL5 varchar(35) = NULL,
  @SendertoReceiverInformationL1 varchar(35) = NULL,
  @SendertoReceiverInformationL2 varchar(35) = NULL,
  @SendertoReceiverInformationL3 varchar(35) = NULL,
  @SendertoReceiverInformationL4 varchar(35) = NULL,
  @SendertoReceiverInformationL5 varchar(35) = NULL,
  @ID numeric(18, 0) out AS BEGIN
INSERT INTO
  dbo.SwiftData (
    MessageReference,
    MessageOrigin,
    OrigineName,
    IncomingOutGoing,
    MessageId,
    SequenceNumber,
    InstructedCurrency,
    InstructedAmount,
    OrderingCustomerL1,
    OrderingCustomerL2,
    OrderingCustomerL3,
    OrderingCustomerL4,
    OrderingCustomerL5,
    IntermediaryInstitutionL1,
    IntermediaryInstitutionL2,
    IntermediaryInstitutionL3,
    IntermediaryInstitutionL4,
    IntermediaryInstitutionL5,
    AccountwithInstitutionL1,
    AccountwithInstitutionL2,
    AccountwithInstitutionL3,
    AccountwithInstitutionL4,
    AccountwithInstitutionL5,
    BeneficiaryCustomerL1,
    BeneficiaryCustomerL2,
    BeneficiaryCustomerL3,
    BeneficiaryCustomerL4,
    BeneficiaryCustomerL5,
    RemittanceInformationL1,
    RemittanceInformationL2,
    RemittanceInformationL3,
    RemittanceInformationL4,
    RemittanceInformationL5,
    SendertoReceiverInformationL1,
    SendertoReceiverInformationL2,
    SendertoReceiverInformationL3,
    SendertoReceiverInformationL4,
    SendertoReceiverInformationL5
  )
output inserted.*
SELECT
  @MessageReference,
  @MessageOrigin,
  @OrigineName,
  @IncomingOutGoing,
  @MessageId,
  @SequenceNumber,
  @InstructedCurrency,
  @InstructedAmount,
  @OrderingCustomerL1,
  @OrderingCustomerL2,
  @OrderingCustomerL3,
  @OrderingCustomerL4,
  @OrderingCustomerL5,
  @IntermediaryInstitutionL1,
  @IntermediaryInstitutionL2,
  @IntermediaryInstitutionL3,
  @IntermediaryInstitutionL4,
  @IntermediaryInstitutionL5,
  @AccountwithInstitutionL1,
  @AccountwithInstitutionL2,
  @AccountwithInstitutionL3,
  @AccountwithInstitutionL4,
  @AccountwithInstitutionL5,
  @BeneficiaryCustomerL1,
  @BeneficiaryCustomerL2,
  @BeneficiaryCustomerL3,
  @BeneficiaryCustomerL4,
  @BeneficiaryCustomerL5,
  @RemittanceInformationL1,
  @RemittanceInformationL2,
  @RemittanceInformationL3,
  @RemittanceInformationL4,
  @RemittanceInformationL5,
  @SendertoReceiverInformationL1,
  @SendertoReceiverInformationL2,
  @SendertoReceiverInformationL3,
  @SendertoReceiverInformationL4,
  @SendertoReceiverInformationL5;
set
  @ID = @@IDENTITY
END
GO