IF OBJECT_ID('SP_Insert_FedMessageByTag', 'P') IS NOT NULL 
BEGIN 
DROP PROC SP_Insert_FedMessageByTag
END
GO
  CREATE PROCEDURE SP_Insert_FedMessageByTag @MessageId varchar(32),
  @MessageReference varchar(32) = NULL,
  @MessageOrigin varchar(10) = NULL,
  @OrigineName varchar(64) = NULL,
  @IncomingOutGoing varchar(16) = NULL,
  @FileId numeric = NULL,
  @ClientId varchar(32) = NULL,
  @DateReceived datetime = NULL,
  @DateLoaded datetime = NULL,
  @OutputCycleDate varchar(10) = NULL,
  @OutputDestinationId varchar(8) = NULL,
  @OutputSequenceNumber varchar(6) = NULL,
  @OutputDateDateMMDD varchar(4) = NULL,
  @OutputTimeHHMM varchar(4) = NULL,
  @OutputApplicationID varchar(4) = NULL,
  @SenderSuppliedInformation varchar(12) = NULL,
  @TypeSubType varchar(4) = NULL,
  @InputMessageAccountabilityData varchar(22) = NULL,
  @SenderDI varchar(27) = NULL,
  @ReceiverDI varchar(27) = NULL,
  @BusinessFunctionCode varchar(3) = NULL,
  @SenderReference varchar(16) = NULL,
  @PreviousMessageId varchar(22) = NULL,
  @LocalInstrument varchar(39) = NULL,
  @PaymentNotification varchar(2328) = NULL,
  @Charges varchar(73) = NULL,
  @InstructedAmount varchar(18) = NULL,
  @ExchangeRate varchar(12) = NULL,
  @IntermediaryFI varchar(175) = NULL,
  @BeneficiaryFI varchar(175) = NULL,
  @Beneficiary varchar(175) = NULL,
  @ReferenceforBeneficiary varchar(16) = NULL,
  @AccountDebitedinDrawdown varchar(175) = NULL,
  @Originator varchar(175) = NULL,
  @OriginatorOptionF varchar(175) = NULL,
  @OriginatorFI varchar(175) = NULL,
  @InstructingFI varchar(175) = NULL,
  @AccountCreditedinDrawdown varchar(9) = NULL,
  @OriginatortoBeneficiaryInformation varchar(140) = NULL,
  @ReceiverFIInformation varchar(195) = NULL,
  @DrawdownDebitAccountAdviceInformation varchar(194) = NULL,
  @IntermediaryFIInformation varchar(195) = NULL,
  @IntermediaryFIAdviceInformation varchar(194) = NULL,
  @BeneficiarysFIInformation varchar(195) = NULL,
  @BeneficiarysFIAdviceInformation varchar(194) = NULL,
  @BeneficiaryInformation varchar(195) = NULL,
  @BeneficiaryAdviceInformation varchar(194) = NULL,
  @MethodofPaymenttoBeneficiary varchar(35) = NULL,
  @FItoFIInformation varchar(210) = NULL,
  @SwiftB33BCurrencyInstructedAmount varchar(23) = NULL,
  @SwiftB50AOrderingCustomer varchar(180) = NULL,
  @SwiftB52AOrderingInstitution varchar(180) = NULL,
  @SwiftB56AIntermediaryInstitution varchar(180) = NULL,
  @SwiftB57AAccountwithInstitution varchar(180) = NULL,
  @SwiftB59ABeneficiaryCustomer varchar(180) = NULL,
  @SwiftB70RemittanceInformation varchar(180) = NULL,
  @SwiftB72SendertoReceiverInformation varchar(180) = NULL,
  @UnstructuredAddendaInformation varchar(Max) = NULL,
  @RelatedRemittanceInformation varchar(2616) = NULL,
  @RemittanceOriginatorInfo varchar(3436) = NULL,
  @RemittanceBeneficiaryInfo varchar(690) = NULL,
  @ActualAmountPaid varchar(22) = NULL,
  @GrossAmountofRemittanceDocument varchar(22) = NULL,
  @SecondaryRemittanceDocumentInformation varchar(109) = NULL,
  @RemittanceFreeText varchar(420) = NULL,
  @PrimaryRemittanceDocumentInformation varchar(109) = NULL,
  @AmountofNegotiatedDiscount varchar(22) = NULL,
  @AdjustmentInformationDetails varchar(168) = NULL,
  @DateofRemittanceDocument varchar(8) = NULL,
  @ServiceMessageInformation varchar(420) = NULL,
  @MessageDisposition varchar(5) = NULL,
  @ReceiptTimeStamp varchar(12) = NULL,
  @OutputMessageAccountabilityData varchar(34) = NULL,
  @Error varchar(41) = NULL,
  @LoadStatus varchar(16) = NULL,
  @LoadRejectReason varchar(512) = NULL,
  @CreationDate datetime = NULL,
  @CreatorId varchar(32) = NULL,
  @UpdateDate datetime = NULL,
  @UpdatorId varchar(32) = NULL,
  @ID numeric(18, 0) out AS BEGIN
INSERT INTO
  dbo.FedMessageByTag (
    MessageId,
    MessageReference,
    MessageOrigin,
    OrigineName,
    IncomingOutGoing,
    FileId,
    ClientId,
    DateReceived,
    DateLoaded,
    OutputCycleDate,
    OutputDestinationId,
    OutputSequenceNumber,
    OutputDateDateMMDD,
    OutputTimeHHMM,
    OutputApplicationID,
    SenderSuppliedInformation,
    TypeSubType,
    InputMessageAccountabilityData,
    SenderDI,
    ReceiverDI,
    BusinessFunctionCode,
    SenderReference,
    PreviousMessageId,
    LocalInstrument,
    PaymentNotification,
    Charges,
    InstructedAmount,
    ExchangeRate,
    IntermediaryFI,
    BeneficiaryFI,
    Beneficiary,
    ReferenceforBeneficiary,
    AccountDebitedinDrawdown,
    Originator,
    OriginatorOptionF,
    OriginatorFI,
    InstructingFI,
    AccountCreditedinDrawdown,
    OriginatortoBeneficiaryInformation,
    ReceiverFIInformation,
    DrawdownDebitAccountAdviceInformation,
    IntermediaryFIInformation,
    IntermediaryFIAdviceInformation,
    BeneficiarysFIInformation,
    BeneficiarysFIAdviceInformation,
    BeneficiaryInformation,
    BeneficiaryAdviceInformation,
    MethodofPaymenttoBeneficiary,
    FItoFIInformation,
    SwiftB33BCurrencyInstructedAmount,
    SwiftB50AOrderingCustomer,
    SwiftB52AOrderingInstitution,
    SwiftB56AIntermediaryInstitution,
    SwiftB57AAccountwithInstitution,
    SwiftB59ABeneficiaryCustomer,
    SwiftB70RemittanceInformation,
    SwiftB72SendertoReceiverInformation,
    UnstructuredAddendaInformation,
    RelatedRemittanceInformation,
    RemittanceOriginatorInfo,
    RemittanceBeneficiaryInfo,
    ActualAmountPaid,
    GrossAmountofRemittanceDocument,
    SecondaryRemittanceDocumentInformation,
    RemittanceFreeText,
    PrimaryRemittanceDocumentInformation,
    AmountofNegotiatedDiscount,
    AdjustmentInformationDetails,
    DateofRemittanceDocument,
    ServiceMessageInformation,
    MessageDisposition,
    ReceiptTimeStamp,
    OutputMessageAccountabilityData,
    Error,
    LoadStatus,
    LoadRejectReason,
    CreationDate,
    CreatorId,
    UpdateDate,
    UpdatorId
  )
  output inserted.*
SELECT
  @MessageId,
  @MessageReference,
  @MessageOrigin,
  @OrigineName,
  @IncomingOutGoing,
  @FileId,
  @ClientId,
  @DateReceived,
  @DateLoaded,
  @OutputCycleDate,
  @OutputDestinationId,
  @OutputSequenceNumber,
  @OutputDateDateMMDD,
  @OutputTimeHHMM,
  @OutputApplicationID,
  @SenderSuppliedInformation,
  @TypeSubType,
  @InputMessageAccountabilityData,
  @SenderDI,
  @ReceiverDI,
  @BusinessFunctionCode,
  @SenderReference,
  @PreviousMessageId,
  @LocalInstrument,
  @PaymentNotification,
  @Charges,
  @InstructedAmount,
  @ExchangeRate,
  @IntermediaryFI,
  @BeneficiaryFI,
  @Beneficiary,
  @ReferenceforBeneficiary,
  @AccountDebitedinDrawdown,
  @Originator,
  @OriginatorOptionF,
  @OriginatorFI,
  @InstructingFI,
  @AccountCreditedinDrawdown,
  @OriginatortoBeneficiaryInformation,
  @ReceiverFIInformation,
  @DrawdownDebitAccountAdviceInformation,
  @IntermediaryFIInformation,
  @IntermediaryFIAdviceInformation,
  @BeneficiarysFIInformation,
  @BeneficiarysFIAdviceInformation,
  @BeneficiaryInformation,
  @BeneficiaryAdviceInformation,
  @MethodofPaymenttoBeneficiary,
  @FItoFIInformation,
  @SwiftB33BCurrencyInstructedAmount,
  @SwiftB50AOrderingCustomer,
  @SwiftB52AOrderingInstitution,
  @SwiftB56AIntermediaryInstitution,
  @SwiftB57AAccountwithInstitution,
  @SwiftB59ABeneficiaryCustomer,
  @SwiftB70RemittanceInformation,
  @SwiftB72SendertoReceiverInformation,
  @UnstructuredAddendaInformation,
  @RelatedRemittanceInformation,
  @RemittanceOriginatorInfo,
  @RemittanceBeneficiaryInfo,
  @ActualAmountPaid,
  @GrossAmountofRemittanceDocument,
  @SecondaryRemittanceDocumentInformation,
  @RemittanceFreeText,
  @PrimaryRemittanceDocumentInformation,
  @AmountofNegotiatedDiscount,
  @AdjustmentInformationDetails,
  @DateofRemittanceDocument,
  @ServiceMessageInformation,
  @MessageDisposition,
  @ReceiptTimeStamp,
  @OutputMessageAccountabilityData,
  @Error,
  @LoadStatus,
  @LoadRejectReason,
  @CreationDate,
  @CreatorId,
  @UpdateDate,
  @UpdatorId;
set
  @ID = @@IDENTITY
END
GO